import type { Screen } from "../types";

export const screens: Screen[] = [
  {
    plane: "public-user",
    slug: "landing",
    title: "Product Landing",
    route: "/",
    designSpecType: "live-route",
    flowNote: "Public first screen with fraud lookup, Safe-Name, and demo transfer CTAs.",
    status: "implemented",
    statusNote: "Route exists and must remain public per T1.",
    workItems: ["FE-LAYOUT-001"],
    requirementRefs: ["T1"],
    implLocation: "src/app/page.tsx",
    engineering: {
      authGate: "public",
      clientActions: ["Open fraud lookup CTA", "Open Safe-Name CTA", "Open demo transfer CTA"],
      serverActions: [],
      dataReads: [],
      dataWrites: [],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "auth-and-access": "The landing page remains public while feature execution moves behind auth.",
      },
    },
  },
  {
    plane: "public-user",
    slug: "auth-verify",
    title: "Email Verification",
    route: "/auth/verify",
    designSpecType: "live-route",
    flowNote: "Collects email verification and returns users to the requested feature route.",
    status: "implemented",
    statusNote: "Route and API flow exist; current verification run determines verified status.",
    workItems: ["FE-AUTH-001", "CMD-AUTH-001"],
    requirementRefs: ["T2", "T6", "REQ-P0-014", "REQ-P0-015"],
    implLocation: "src/app/auth/verify/page.tsx",
    engineering: {
      authGate: "public verification entry",
      clientActions: ["Request verification code", "Submit verification code", "Follow redirect target"],
      serverActions: ["POST /api/v1/auth/verify-email"],
      dataReads: ["User verification state"],
      dataWrites: ["User email verification state"],
      telemetryEvents: [],
      exceptionStates: ["email-policy"],
      controlAreaNotes: {
        "auth-and-access": "Feature routes use this screen as the auth gate.",
        "email-failure-policy": "Verification-code email failure blocks the request with HTTP 502.",
      },
    },
  },
  {
    plane: "public-user",
    slug: "fraud-lookup",
    title: "Fraud Lookup",
    route: "/fraud-lookup",
    designSpecType: "live-route",
    flowNote: "Lookup result drives prefilled fraud report submission.",
    status: "implemented",
    statusNote: "Lookup and report UX exists with auth-gated route expectations.",
    workItems: ["FE-FRAUD-001", "FE-FRAUD-002", "QRY-FRAUD-001", "CMD-FRAUD-001"],
    requirementRefs: ["T2", "T4", "REQ-P0-001", "REQ-P0-002", "REQ-P0-003", "REQ-P0-004", "REQ-P0-005"],
    implLocation: "src/app/fraud-lookup/page.tsx",
    engineering: {
      authGate: "email verified",
      clientActions: ["Submit address lookup", "Report this address", "Submit incident details and evidence URL"],
      serverActions: ["GET /api/v1/fraud/lookup", "POST /api/v1/fraud/report"],
      dataReads: ["FraudAddress", "FraudReport aggregate count"],
      dataWrites: ["FraudReport"],
      telemetryEvents: [],
      exceptionStates: ["email-policy", "api-contract"],
      controlAreaNotes: {
        "auth-and-access": "Feature execution requires email authentication.",
        "fraud-lookup-reporting": "Report form is entered from lookup result and prefilled with address and chain.",
        "api-response-contract": "Lookup and report APIs must use the central response envelope.",
        "email-failure-policy": "Report receipt email failures are log-only after the DB mutation succeeds.",
      },
    },
  },
  {
    plane: "public-user",
    slug: "safe-name-wizard",
    title: "Safe-Name Wizard",
    route: "/safe-name",
    designSpecType: "live-route",
    flowNote: "Sequential registration, resolve/fraud check, and demo transfer simulation.",
    status: "implemented",
    statusNote: "Wizard route exists; current E2E run determines verified status.",
    workItems: ["FE-SN-001", "FE-SN-002", "CMD-SN-001", "QRY-SN-001", "CMD-TX-001"],
    requirementRefs: ["T2", "T3", "REQ-P0-006", "REQ-P0-007", "REQ-P0-008", "REQ-P0-009", "REQ-P0-010", "REQ-P0-016", "REQ-P0-019"],
    implLocation: "src/app/safe-name/page.tsx",
    engineering: {
      authGate: "email verified",
      clientActions: ["Register Safe-Name", "Resolve Safe-Name", "Confirm fraud status", "Simulate demo transfer"],
      serverActions: ["POST /api/v1/safename/register", "GET /api/v1/resolve", "POST /api/v1/transfer/demo"],
      dataReads: ["SafeName", "FraudAddress"],
      dataWrites: ["SafeName", "TransferDemo"],
      telemetryEvents: [],
      exceptionStates: ["email-policy", "api-contract"],
      controlAreaNotes: {
        "auth-and-access": "Feature execution requires email authentication.",
        "safe-name-transfer": "The route is a sequential wizard with values carried forward between steps.",
        "api-response-contract": "Register, resolve, and transfer APIs use the shared response envelope.",
        "email-failure-policy": "Demo transfer notification failures are log-only after the DB mutation succeeds.",
      },
    },
  },
  {
    plane: "operator",
    slug: "admin-login",
    title: "Admin Login",
    route: "/auth/admin-login",
    designSpecType: "live-route",
    flowNote: "Operator authentication entry before the approval dashboard.",
    status: "implemented",
    statusNote: "Admin login route exists.",
    workItems: ["FE-AUTH-002", "CMD-AUTH-002"],
    requirementRefs: ["REQ-P0-011"],
    implLocation: "src/app/auth/admin-login/page.tsx",
    engineering: {
      authGate: "public operator login",
      clientActions: ["Submit operator credentials"],
      serverActions: ["POST /api/v1/admin/login"],
      dataReads: ["Operator"],
      dataWrites: ["Operator session token"],
      telemetryEvents: [],
      exceptionStates: ["api-contract"],
      controlAreaNotes: {
        "auth-and-access": "Operator access is separate from public email verification.",
        "api-response-contract": "Admin login uses the shared response envelope.",
      },
    },
  },
  {
    plane: "operator",
    slug: "approval-dashboard",
    title: "Approval Dashboard",
    route: "/admin/approval",
    designSpecType: "live-route",
    flowNote: "Operator reviews report quality context before approval or rejection.",
    status: "implemented",
    statusNote: "Admin dashboard exists and is linked to approval API behavior.",
    workItems: ["FE-ADMIN-001", "QRY-ADMIN-001", "CMD-ADMIN-001"],
    requirementRefs: ["T5", "REQ-P0-011", "REQ-P0-012", "REQ-P0-013"],
    implLocation: "src/app/admin/approval/page.tsx",
    engineering: {
      authGate: "operator authenticated",
      clientActions: ["Review pending reports", "Approve report", "Reject report"],
      serverActions: ["POST /api/v1/admin/approve"],
      dataReads: ["FraudReport", "FraudAddress", "Reporter history"],
      dataWrites: ["FraudReport decision", "FraudAddress state"],
      telemetryEvents: [],
      exceptionStates: ["email-policy", "api-contract"],
      controlAreaNotes: {
        "auth-and-access": "Operator session is required for approval.",
        "admin-approval-quality": "Dashboard must show report and reporter quality context before approval.",
        "api-response-contract": "Approval mutation uses the shared response envelope.",
        "email-failure-policy": "Admin result notification failures are log-only.",
      },
    },
  },
  {
    plane: "system-state",
    slug: "api-contract",
    title: "API Response Contract",
    route: "/api/v1/*",
    designSpecType: "system-contract",
    flowNote: "Central response helpers define success and error envelopes for Phase-0 APIs.",
    status: "implemented",
    statusNote: "Shared helpers exist in src/lib/api-response.ts.",
    workItems: ["API-001", "CMD-AUTH-002", "QRY-FRAUD-001", "CMD-SN-001", "QRY-SN-001", "CMD-ADMIN-001"],
    requirementRefs: ["T7"],
    implLocation: "src/lib/api-response.ts",
    engineering: {
      authGate: "route-specific",
      clientActions: [],
      serverActions: ["successResponse", "errorResponse", "withErrorHandler"],
      dataReads: [],
      dataWrites: [],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "api-response-contract": "All Phase-0 /api/v1/* route handlers should use the central helpers.",
      },
    },
  },
  {
    plane: "system-state",
    slug: "email-policy",
    title: "Email Failure Policy",
    route: "src/lib/email.ts",
    designSpecType: "system-contract",
    flowNote: "Differentiates blocking verification email failures from log-only notifications.",
    status: "implemented",
    statusNote: "Email helper and API call sites exist.",
    workItems: ["CMD-AUTH-001", "CMD-FRAUD-001", "CMD-TX-001"],
    requirementRefs: ["T6"],
    implLocation: "src/lib/email.ts",
    engineering: {
      authGate: "route-specific",
      clientActions: [],
      serverActions: ["Send verification code", "Send report receipt", "Send admin result", "Send demo transfer notification"],
      dataReads: [],
      dataWrites: ["Email delivery attempt logs"],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "email-failure-policy": "Verification email failure blocks auth; notification email failures are log-only.",
      },
    },
  },
  {
    plane: "system-state",
    slug: "seed-scale",
    title: "Seed Scale and Cost Gates",
    route: "prisma/seed.ts",
    designSpecType: "system-contract",
    flowNote: "Reduced Phase-0 seed scale and cost gates are used for acceptance.",
    status: "implemented",
    statusNote: "Seed script and SRS cost gates exist.",
    workItems: ["SEED-003", "NFR-004"],
    requirementRefs: ["T9", "T10", "REQ-P0-NF-005", "REQ-P0-NF-008", "REQ-P0-NF-009"],
    implLocation: "prisma/seed.ts",
    engineering: {
      authGate: "not user-facing",
      clientActions: [],
      serverActions: ["Seed reduced Phase-0 data"],
      dataReads: ["SRS cost gates"],
      dataWrites: ["Seeded database fixtures"],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "seed-scale-cost": "Seed and cost gates follow T9 and T10.",
      },
    },
  },
  {
    plane: "system-state",
    slug: "phase0-e2e-gate",
    title: "Phase-0 E2E Gate",
    route: "e2e/phase0-reqs.spec.ts",
    designSpecType: "test-gate",
    flowNote: "Playwright automation covers REQ-P0-001 through REQ-P0-019.",
    status: "implemented",
    statusNote: "Specs exist; this implementation run will report whether the suite is green.",
    workItems: ["TEST-022"],
    requirementRefs: ["T8", "REQ-P0-001~019"],
    implLocation: "e2e/phase0-reqs.spec.ts",
    engineering: {
      authGate: "not user-facing",
      clientActions: [],
      serverActions: ["Run Playwright suite"],
      dataReads: ["E2E memory DB fixtures"],
      dataWrites: ["Test database state"],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "e2e-phase-gate": "Phase-0 completion requires the Playwright suite to be green.",
      },
    },
  },
];
