import type { WorkItem } from "../types";

export const workItems: WorkItem[] = [
  {
    id: "FE-LAYOUT-001",
    title: "Phase-0 public landing with three CTAs",
    phase: "Phase 0 UI",
    status: "done",
    externalRefs: ["T1"],
    dependsOn: [],
    screens: ["public-user/landing"],
    doc: "tasks/0.TASKS_LIST_v0_2_opus47_fn.md",
  },
  {
    id: "FE-AUTH-001",
    title: "Email verification entry and redirect flow",
    phase: "Phase 0 Auth",
    status: "done",
    externalRefs: ["T2", "REQ-P0-014", "REQ-P0-015"],
    dependsOn: ["API-001"],
    screens: ["public-user/auth-verify"],
    doc: "tasks/0.TASKS_LIST_v0_2_opus47_fn.md",
  },
  {
    id: "FE-AUTH-002",
    title: "Admin login entry",
    phase: "Phase 0 Auth",
    status: "done",
    externalRefs: ["REQ-P0-011"],
    dependsOn: ["CMD-AUTH-002"],
    screens: ["operator/admin-login"],
    doc: "tasks/0.TASKS_LIST_v0_2_opus47_fn.md",
  },
  {
    id: "FE-FRAUD-001",
    title: "Fraud lookup page",
    phase: "Phase 0 Fraud",
    status: "done",
    externalRefs: ["T4", "REQ-P0-001", "REQ-P0-002"],
    dependsOn: ["QRY-FRAUD-001"],
    screens: ["public-user/fraud-lookup"],
    doc: "tasks/0.TASKS_LIST_v0_2_opus47_fn.md",
  },
  {
    id: "FE-FRAUD-002",
    title: "Lookup-driven fraud report UX",
    phase: "Phase 0 Fraud",
    status: "done",
    externalRefs: ["T4", "REQ-P0-003", "REQ-P0-004", "REQ-P0-005"],
    dependsOn: ["FE-FRAUD-001", "CMD-FRAUD-001"],
    screens: ["public-user/fraud-lookup"],
    doc: "tasks/0.TASKS_LIST_v0_2_opus47_fn.md",
  },
  {
    id: "FE-SN-001",
    title: "Sequential Safe-Name wizard",
    phase: "Phase 0 Safe-Name",
    status: "done",
    externalRefs: ["T3", "REQ-P0-006", "REQ-P0-007", "REQ-P0-008"],
    dependsOn: ["CMD-SN-001", "QRY-SN-001"],
    screens: ["public-user/safe-name-wizard"],
    doc: "tasks/0.TASKS_LIST_v0_2_opus47_fn.md",
  },
  {
    id: "FE-SN-002",
    title: "Safe-Name resolve and transfer simulation UX",
    phase: "Phase 0 Safe-Name",
    status: "done",
    externalRefs: ["REQ-P0-009", "REQ-P0-010", "REQ-P0-016", "REQ-P0-019"],
    dependsOn: ["FE-SN-001", "CMD-TX-001"],
    screens: ["public-user/safe-name-wizard"],
    doc: "tasks/0.TASKS_LIST_v0_2_opus47_fn.md",
  },
  {
    id: "FE-ADMIN-001",
    title: "Admin approval dashboard with quality context",
    phase: "Phase 0 Admin",
    status: "done",
    externalRefs: ["T5", "REQ-P0-011", "REQ-P0-012", "REQ-P0-013"],
    dependsOn: ["QRY-ADMIN-001", "CMD-ADMIN-001"],
    screens: ["operator/approval-dashboard"],
    doc: "tasks/0.TASKS_LIST_v0_2_opus47_fn.md",
  },
  {
    id: "API-001",
    title: "Central API response envelope",
    phase: "Phase 0 API",
    status: "done",
    externalRefs: ["T7"],
    dependsOn: [],
    screens: ["system-state/api-contract"],
    doc: "src/lib/api-response.ts",
  },
  {
    id: "CMD-AUTH-001",
    title: "Verification code email request",
    phase: "Phase 0 Auth",
    status: "done",
    externalRefs: ["T6"],
    dependsOn: ["API-001"],
    screens: ["public-user/auth-verify", "system-state/email-policy"],
    doc: "src/app/api/v1/auth/verify-email/route.ts",
  },
  {
    id: "CMD-AUTH-002",
    title: "Admin login mutation",
    phase: "Phase 0 Auth",
    status: "done",
    externalRefs: ["REQ-P0-011"],
    dependsOn: ["API-001"],
    screens: ["operator/admin-login", "system-state/api-contract"],
    doc: "src/app/api/v1/admin/login/route.ts",
  },
  {
    id: "QRY-FRAUD-001",
    title: "Fraud address lookup query",
    phase: "Phase 0 Fraud",
    status: "done",
    externalRefs: ["REQ-P0-001", "REQ-P0-002"],
    dependsOn: ["API-001"],
    screens: ["public-user/fraud-lookup", "system-state/api-contract"],
    doc: "src/app/api/v1/fraud/lookup/route.ts",
  },
  {
    id: "CMD-FRAUD-001",
    title: "Fraud report submission",
    phase: "Phase 0 Fraud",
    status: "done",
    externalRefs: ["REQ-P0-003", "REQ-P0-004", "REQ-P0-005"],
    dependsOn: ["API-001", "QRY-FRAUD-001"],
    screens: ["public-user/fraud-lookup", "system-state/email-policy"],
    doc: "src/app/api/v1/fraud/report/route.ts",
  },
  {
    id: "CMD-SN-001",
    title: "Safe-Name registration command",
    phase: "Phase 0 Safe-Name",
    status: "done",
    externalRefs: ["REQ-P0-006", "REQ-P0-007"],
    dependsOn: ["API-001"],
    screens: ["public-user/safe-name-wizard", "system-state/api-contract"],
    doc: "src/app/api/v1/safename/register/route.ts",
  },
  {
    id: "QRY-SN-001",
    title: "Safe-Name resolve query",
    phase: "Phase 0 Safe-Name",
    status: "done",
    externalRefs: ["REQ-P0-008", "REQ-P0-009"],
    dependsOn: ["API-001"],
    screens: ["public-user/safe-name-wizard", "system-state/api-contract"],
    doc: "src/app/api/v1/resolve/route.ts",
  },
  {
    id: "CMD-TX-001",
    title: "Demo transfer command",
    phase: "Phase 0 Safe-Name",
    status: "done",
    externalRefs: ["REQ-P0-016", "REQ-P0-017", "REQ-P0-018", "REQ-P0-019"],
    dependsOn: ["QRY-SN-001"],
    screens: ["public-user/safe-name-wizard", "system-state/email-policy"],
    doc: "src/app/api/v1/transfer/demo/route.ts",
  },
  {
    id: "QRY-ADMIN-001",
    title: "Admin dashboard review data",
    phase: "Phase 0 Admin",
    status: "done",
    externalRefs: ["T5", "REQ-P0-011", "REQ-P0-012"],
    dependsOn: ["CMD-AUTH-002"],
    screens: ["operator/approval-dashboard"],
    doc: "src/app/admin/approval/page.tsx",
  },
  {
    id: "CMD-ADMIN-001",
    title: "Admin approval command",
    phase: "Phase 0 Admin",
    status: "done",
    externalRefs: ["REQ-P0-013"],
    dependsOn: ["QRY-ADMIN-001"],
    screens: ["operator/approval-dashboard", "system-state/api-contract"],
    doc: "src/app/api/v1/admin/approve/route.ts",
  },
  {
    id: "SEED-003",
    title: "Reduced Phase-0 seed scale",
    phase: "Phase 0 Data",
    status: "done",
    externalRefs: ["T9"],
    dependsOn: [],
    screens: ["system-state/seed-scale"],
    doc: "prisma/seed.ts",
  },
  {
    id: "TEST-022",
    title: "Phase-0 Playwright E2E gate",
    phase: "Phase 0 Verification",
    status: "done",
    externalRefs: ["T8", "REQ-P0-001~019"],
    dependsOn: ["FE-FRAUD-002", "FE-SN-002", "FE-ADMIN-001"],
    screens: ["system-state/phase0-e2e-gate"],
    doc: "e2e/phase0-reqs.spec.ts",
  },
  {
    id: "NFR-004",
    title: "Cost and scalability gates",
    phase: "Phase 0 Non-functional",
    status: "done",
    externalRefs: ["T10", "REQ-P0-NF-005", "REQ-P0-NF-008", "REQ-P0-NF-009"],
    dependsOn: ["SEED-003"],
    screens: ["system-state/seed-scale"],
    doc: "docs/0.SRS_v1opus46_fn.md",
  },
  {
    id: "PB-001",
    title: "PlayBoard registry scaffold",
    phase: "PlayBoard",
    status: "done",
    externalRefs: ["PlayBoard Wave 1"],
    dependsOn: [],
    screens: [],
    doc: "reference/PLAYBOARD_IMPLEMENTATION_PLAN.md",
  },
  {
    id: "PB-002",
    title: "PlayBoard derived selectors",
    phase: "PlayBoard",
    status: "done",
    externalRefs: ["PlayBoard Wave 2"],
    dependsOn: ["PB-001"],
    screens: [],
    doc: "reference/PLAYBOARD_IMPLEMENTATION_PLAN.md",
  },
  {
    id: "PB-003",
    title: "PlayBoard integrity checks",
    phase: "PlayBoard",
    status: "done",
    externalRefs: ["PlayBoard Wave 2"],
    dependsOn: ["PB-002"],
    screens: [],
    doc: "reference/PLAYBOARD_IMPLEMENTATION_PLAN.md",
  },
  {
    id: "PB-004",
    title: "PlayBoard route shell and exposure gate",
    phase: "PlayBoard",
    status: "done",
    externalRefs: ["PlayBoard Wave 3"],
    dependsOn: ["PB-003"],
    screens: [],
    doc: "reference/PLAYBOARD_IMPLEMENTATION_PLAN.md",
  },
  {
    id: "PB-005",
    title: "PlayBoard core board views",
    phase: "PlayBoard",
    status: "done",
    externalRefs: ["PlayBoard Wave 4"],
    dependsOn: ["PB-004"],
    screens: [],
    doc: "reference/PLAYBOARD_IMPLEMENTATION_PLAN.md",
  },
  {
    id: "PB-006",
    title: "PlayBoard flow and screen surfaces",
    phase: "PlayBoard",
    status: "done",
    externalRefs: ["PlayBoard Wave 5"],
    dependsOn: ["PB-005"],
    screens: [],
    doc: "reference/PLAYBOARD_IMPLEMENTATION_PLAN.md",
  },
  {
    id: "PB-007",
    title: "PlayBoard governance and tests",
    phase: "PlayBoard",
    status: "done",
    externalRefs: ["PlayBoard Wave 7"],
    dependsOn: ["PB-006"],
    screens: [],
    doc: "reference/PLAYBOARD_IMPLEMENTATION_PLAN.md",
  },
  {
    id: "PB-008",
    title: "PlayBoard capture pipeline",
    phase: "PlayBoard",
    status: "not_started",
    externalRefs: ["PlayBoard Wave 6"],
    dependsOn: ["PB-006"],
    screens: [],
    doc: "reference/PLAYBOARD_IMPLEMENTATION_PLAN.md",
  },
];
